### ISSUE TITLE
Any future support for nginx/apache ?

### ISSUE THREAD

**Issue by kaitoAckerman** [bitnami/bitnami-docker-laravel#100]
Hello there,

Is there any support for nginx/apache instead of only `php artisan serve` by default ? Is `php artisan serve` save for production server ? 

Thank you.

**Comment by andresbono** [comment]
Hi @kaitoAckerman, this is a development container so it is recommended that you move the php code to a different container instead of serving it with `php artisan serve` in production.

Maybe the combination of nginx/apache + php-fpm suits your needs. Take a look at https://github.com/bitnami/bitnami-docker-php-fpm#connecting-to-other-containers.

**Comment by kaitoAckerman** [comment]
Alright then. Thanks for your guide @andresbono .
