### ISSUE TITLE
How to choose a different version of Laravel?

### ISSUE THREAD

**Issue by pato-pato** [bitnami/bitnami-docker-laravel#116]
Hi,

I'm new to the docker world and my question is about how to use this Docker Compose environment and change the required version of Laravel that I need?

I did try this version for projects I already have and it works well but this uses the newer version of Laravel. How can I use this docker environment but for **Laravel 5.5**?

Is it related to **tags**? If so, how should I use them!?

Thanks,

**Comment by alemorcuq** [comment]
Hi, @pato-pato.

Unfortunately, we don't support Laravel 5.5 anymore. You would have to use an old image, which we can't really recommend because despite Laravel 5.5 being an LTS release we haven't packaged it in a long time and they are not up to date.

Regarding your question about tags, you specify them after the image name. For example, to use the `latest` tag for `bitnami/laravel`, you have to use the `bitnami/laravel:latest` image. You can find a list of all the tags in [Docker Hub](https://hub.docker.com/r/bitnami/laravel/tags), but please keep in mind that we don't recommend using unmaintained tags.

Regards,
Alejandro

**Comment by pato-pato** [comment]
Thank you @alemorcuq for your quick response!

Have a good day!
