### ISSUE TITLE
Browsersync

### ISSUE THREAD

**Issue by runthis** [bitnami/bitnami-docker-laravel#145]
**Description**

Awesome and easy setup you have here :-)

Having an issue with BrowserSync support. It appears as though, when using BrowserSync, the URL to visit (default localhost:3001) infinitely loads and does not complete. however the BrowserSync UI on port 3002 loads just fine. Any change I should make to get that to work? Setup is pretty standard, haven't made any real changes.

**Steps to reproduce the issue:**

1. Follow all steps for setting up a new container
2. Add mix.browserSync(); (and do the whole npm install stuffs if needed)
3. npm run watch

**Comment by alvneiayu** [comment]
hi @runthis 

Could you share with me your docker-compose configuration or your docker-run command, please? Just to reproduce the same scenario than you.

Thanks a lot

Álvaro

**Comment by runthis** [comment]
@alvneiayu it is the default docker-compose.yml with no changes.

**Comment by alvneiayu** [comment]
hi @runthis 

Could you try to access using http://127.0.0.1:3001 instead of http://localhost:30001, please? I reproduced your problem and I think that it is a problem with the proxy configuration (I am not expert in Laravel).

Also, I found this stackoverflow case reproducing the same problem than you:

https://stackoverflow.com/questions/49691857/laravel-mix-browsersync-infinite-loading-out-of-the-box

Note: I included the ports inside the docker-compose before to install browsersync:

```
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002
```

Let me know if you still have problems. Thanks a lot

Álvaro
