### ISSUE TITLE
how to install phpmyadmin

### ISSUE THREAD

**Issue by cristiancmello** [bitnami/bitnami-docker-laravel#16]
How to install phpMyAdmin to use with MariaDB and get access to browser (eg '/phpmyadmin', Codenvy)?

**Comment by alexandernst** [comment]
Hi!

This docker is intended for laravel development, and because of that it's not using a (what you'd call) "real" web server (like NGINX or Apache), but laravel's built-in web server. Because of that, installing phpMyAdmin won't be that easy.

Anyways, if you're brave enough, my take on that would be:

1. Run the docker
2. SSH into it and install NGINX (`apt-get install nginx`)
3. `wget/curl` latest stable version of phpMyAdmin (to `/opt/phpMyAdmin` for example)
4. Create 2 servers with NGINX's config, one pointing to `/app` (which is where the laravel project is located), the other one to where you downloaded and extracted phpMyAdmin.
5. Since the container exposes port 3000, it would be easier to make NGINX listen to that port (instead of the default 80) instead of changing the container.
6. Last but not less important, don't forget to modify your `hosts` file and point the domains for the servers you created in NGINX's config to your docker container (if you're using native docker, that would be `localhost`, else it would be the IP of the virtual machine you're using).

I hope that helps !

**Comment by cristiancmello** [comment]
Thanks for answer! I'll try what you suggested. I really enjoyed this Bitnami's container.
